name: Deploy Site

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@master
      with:
        submodules: recursive
  
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x.x' # SDK Version to use.
  
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - run: dotnet run --project .\test-automation.dev\test-automation.dev.csproj -- deploy
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./test-automation.dev/output

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2